language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t maciej55/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true maciej55/react-test npm test

after_success:
  - docker build -t maciej55/multi-client ./client
  - docker build -t maciej55/multi-nginx ./nginx
  - docker build -t maciej55/multi-server ./server
  - docker build -t maciej55/multi-worker ./worker